name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

env:
  RG_NAME: adogithubtf-rg
  LOCATION: uksouth
  IMAGE_NAME: ado-github-terraform-demo
  ACR_LOGIN_SERVER: acradogithubtf.azurecr.io

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username:     ${{ secrets.ACR_USERNAME }}
          password:     ${{ secrets.ACR_PASSWORD }}

      - name: Build & push image
        run: |
          docker build -t $ACR_LOGIN_SERVER/${IMAGE_NAME}:latest ./app
          docker push    $ACR_LOGIN_SERVER/${IMAGE_NAME}:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -input=false
        env:
          ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform apply
        run: |
          terraform apply -auto-approve \
            -var "rg_name=${{ env.RG_NAME }}" \
            -var "location=${{ env.LOCATION }}" \
            -var "acr_suffix=adogithubtf" \
            -var "image_name=${{ env.IMAGE_NAME }}"
        env:
          ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
